views:
  - name: File
    title: Files
    itemName: Name
    types:
      - https://sils.uva.nl/ontology#ExternalFile
    columns:
      - name: externalFileLink
        title: File link
        source: https://sils.uva.nl/ontology#externalFileLink
        type: text
    joinColumns:
      - name: studyName
        title: Study name
        source: http://www.w3.org/2000/01/rdf-schema#label
        sourceClass: https://sils.uva.nl/ontology#Study
        sourceClassName: Study
        type: text
      - name: projectName
        title: Project name
        source: http://www.w3.org/2000/01/rdf-schema#label
        sourceClass: https://sils.uva.nl/ontology#Project
        sourceClassName: Project
        type: text
#      - name: studyDescription
#        title: Study description
#        source: http://www.w3.org/2000/01/rdf-schema#label
#        sourceClass: https://sils.uva.nl/ontology#Study
#        sourceClassName: Study
#        type: text

